### ISSUE TITLE
[jsk_naoqi_robot/README] Python NAOqi SDK 2.5.5より小さい時（例 2.1.4)のパスの通し方が違う

### ISSUE THREAD

**Issue by kochigami** [jsk-ros-pkg/jsk_robot#1099]
READMEにしたがって，Python NAOqi API 2.1.4を入れた．
`export PYTHONPATH=$HOME/pynaoqi/<your Python SDK package name>:$PYTHONPATH`
を`.bashrc`に書いた．

ROS kinetic, ubuntu 16.04

```
roslaunch nao_bringup nao_full.launch network_interface:=xxx
```
でパスが通っていないとエラーが出る．
```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/naoqi_pose/pose_controller.py", line 49, in <module>
    from naoqi_driver.naoqi_node import NaoqiNode
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/naoqi_driver/__init__.py", line 29, in <module>
    from .naoqi_node import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/naoqi_driver/naoqi_node.py", line 37, in <module>
    raise RuntimeError("Error importing NaoQI. Please make sure that Aldebaran's NaoQI API is in your PYTHONPATH.")
RuntimeError: Error importing NaoQI. Please make sure that Aldebaran's NaoQI API is in your PYTHONPATH.
[nao_robot/pose/pose_controller-3] process has died [pid 14925, exit code 1, cmd /opt/ros/kinetic/lib/naoqi_pose/pose_controller.py --pip=133.11.216.73 --pport=9559 __name:=pose_controller __log:=/home/kanae/.ros/log/8c47ed2e-8293-11e9-8e33-e86a6433c67f/nao_robot-pose-pose_controller-3.log].
log file: /home/kanae/.ros/log/8c47ed2e-8293-11e9-8e33-e86a6433c67f/nao_robot-pose-pose_controller-3*.log
```

**Comment by kochigami** [comment]
naoqi_poseのコードが変わったか，SDKのnaoqi.pyの中身が2.1,4と2.5.5で変わったのかな？と思う．
原因究明は大変そうだし，ナオでも2.5.5のSDKで動くので，これで使えばいいと思う．．．

少し調べると，
- 2.5.5のpython SDKと2.1.4のpython SDKのnaoqi.pyの中身が違う．これは前からなのか？
- 2.1.4のpython SDKだとROSノードのみ立ち上がらない
2.1.4のパスを通しておいて以下を実行するとナオがしゃべる
```
python
>>> import naoqi
>>> from naoqi import ALProxy
>>> tts = ALProxy("ALTextToSpeech", "nao.local", 9559)
hogehogehoge
>>> tts.say("hello")
```
でしゃべる

2.1.4のパスを通しておいて以下を実行すると，以下のエラーが出る．
`roslaunch jsk_nao_startup jsk_nao_startup.launch network_interface:=<your network interface> launch_joy:=false`
naoqi_pose/pose_controller.pyの実行時
```
  File "/home/kanae/catkin_ws/src/naoqi_bridge/naoqi_driver_py/src/naoqi_driver/naoqi_node.py", line 37, in <module>
    raise RuntimeError("Error importing NaoQI. Please make sure that Aldebaran's NaoQI API is in your PYTHONPATH.")
RuntimeError: Error importing NaoQI. Please make sure that Aldebaran's NaoQI API is in your PYTHONPATH.
```
