### ISSUE TITLE
[spot_autowalk_data] Fail to visualize the map of some autowalk data when using view_map.py

### ISSUE THREAD

**Issue by tkmtnt7000** [jsk-ros-pkg/jsk_robot#1402]
This issue depends on the branch `develop/spot(sktometometo/jsk_robot)` now.
(`jsk_spot_robot` have not merged yet, but I think it is important to keep a history of the problem, so I've created this issue in jsk-ros-pkg/jsk_robot. (I tried to create this issue in `sktometometo/jsk_robot`, but Issues cannot be created in fork repositries...))
Cc:@sktometometo

When running view_map.py with some autowalk data, a map is not visualized and I get an error like following.
```bash
tsukamoto@tsukamoto-HP-Z800:~/ros/spot_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spot_autowalk_data/autowalk$ rosrun spot_autowalk_data view_map.py eng2_GarbageCollectionArea_inside_counterclockwise.walk
Traceback (most recent call last):
  File "/home/tsukamoto/ros/spot_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spot_autowalk_data/scripts/view_map.py", line 401, in <module>
    main( args.map_directory, False )
  File "/home/tsukamoto/ros/spot_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spot_autowalk_data/scripts/view_map.py", line 355, in main
    current_edge_snapshots) = load_map(path)
  File "/home/tsukamoto/ros/spot_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spot_autowalk_data/scripts/view_map.py", line 260, in load_map
    with open(file_name, "rb") as snapshot_file:
IsADirectoryError: [Errno 21] Is a directory: 'eng2_GarbageCollectionArea_inside_counterclockwise.walk/edge_snapshots/'
```
However, `'eng2_GarbageCollectionArea_inside_counterclockwise.walk/edge_snapshots/'` has files like following ..., so files under this directory seem to be inaccessible.

<details open>

<summary> files in edge_snapshots directory</summary>

```bash
tsukamoto@tsukamoto-HP-Z800:~/ros/spot_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spot_autowalk_data/autowalk/eng2_GarbageCollectionArea_inside_counterclockwise.walk/edge_snapshots$ ls
'edge_snapshot_id_atonic-redbug-MV0t.PHftX9GqtQ7UztK8Q=='
'edge_snapshot_id_beige-volvox-mjxLJYEyShw8blIWWWYiRQ=='
'edge_snapshot_id_blocky-fowl-L2EuyeEGFzlcullfkouN1A=='
'edge_snapshot_id_bosky-minnow-bjLmiZIIwDvkJ7Cgq6Igyg=='
'edge_snapshot_id_cowled-pug-d890.MZfDwnbqBOFJULXUA=='
'edge_snapshot_id_dexter-remora-f.MoxOt874U2LCRHjEn+Aw=='
'edge_snapshot_id_fused-ibex-Ou7SzM6merfK6Xj0F3OFGg=='
'edge_snapshot_id_grainy-rodent-Lq4UGNcVg8Ow1k66SjXMgA=='
'edge_snapshot_id_groggy-condor-yl6n1x0JzJLZGKapdbnHxg=='
'edge_snapshot_id_hempen-equid-1OnWqXm8iwAFMbjBRFG0lA=='
'edge_snapshot_id_none-carp-2VmIOIUOFf7mNgUi7Bv4yg=='
'edge_snapshot_id_raspy-mouse-3rX3Li8PiwNP0qHCPqq1HA=='
'edge_snapshot_id_reflex-puma-A4a1xXea5m2cu2tpXpGDGA=='
'edge_snapshot_id_rust-manx-XL7zMDB+GaPieBY0ZhPQ0w=='
'edge_snapshot_id_screwy-baboon-8jqrfj6bjlYmsiXp2piz2w=='
'edge_snapshot_id_slimed-shrew-PIif2iEcZQCyzmhH+xY24Q=='
'edge_snapshot_id_sneaky-gnu-HpalyBCVOLqNaarz8yLZ3A=='
'edge_snapshot_id_uncool-earwig-eqf29p7BcRChR0SgP7T1Yw=='
'edge_snapshot_id_west-dugong-.frxT4uePT8W6ts9fUH6dw=='

```

</details>

The same situations occurred when showing map of `eng2_1FElevator_to_GarbageCollectionArea_inside_clockwise.walk`

**Comment by tkmtnt7000** [comment]
This issue is solved by https://github.com/sktometometo/jsk_robot/pull/155.
