### ISSUE TITLE
[Spot][BelKa] sometimes internal image service has problems

### ISSUE THREAD

**Issue by sktometometo** [jsk-ros-pkg/jsk_robot#1898]
Sometime belka cannot send image. During this process, 

- Spot cannot walk
- Spot cannot send image
- Spot cannot execute autowalk

This error disappears few ten seconds after it shows up.

spot_driver generate error like below.

```bash
[ERROR] [WallTime: 1701916688.056041] [node:/spot/spot_ros] [func:AsyncImageService._handle_error]: Failure getting robot_image_service: ServiceUnavailableError: The proxy could not find th
e (possibly unregistered) service.            
Traceback (most recent call last):                                                                         
  File "/home/sktometometo/.local/lib/python3.6/site-packages/bosdyn/client/async_tasks.py", line 86, in update
    self._handle_result(self._future.result())                                                                                                        
  File "/home/sktometometo/.local/lib/python3.6/site-packages/bosdyn/client/common.py", line 532, in result                                                                                      raise error                                               
bosdyn.client.exceptions.ServiceUnavailableError: ServiceUnavailableError: The proxy could not find the (possibly unregistered) service.
```

During this process, tablet shows like below

TODO

And front LED of BelKa blinks orange, which is different from usual state (blue or green)

TODO

**Comment by sktometometo** [comment]
It seems to be resolved by cooling and cleaning.
