### ISSUE TITLE
[jsk_pepper_robot] jsk_pepper_startup.launchの立ち上がりが遅いか, 立ち上がらないことがある

### ISSUE THREAD

**Issue by kochigami** [jsk-ros-pkg/jsk_robot#567]
```roslaunch jsk_pepper_startup jsk_pepper_startup.launch```を実行した時，中に含まれる```naoqi_driver/launch/naoqi_driver.launch```の立ち上がりが遅い時がある．（またはnaoqi_dashboardのノードが落ちて，naoqi_driver.launchも上がらないこともある　（ログは取り忘れ））

可能性は，
起動直後　or
AutonomousLifeがsolitaryかinteractive 
ではないか．
分かったらこのissueを閉じる．

```roslaunch jsk_pepper_startup jsk_pepper_startup.launch```の実行結果
###ここで止まる###　で止まる（```naoqi_driver```の立ち上がる前の部分）
```
 roslaunch jsk_pepper_startup jsk_pepper_startup.launch network_interface:=eth1
... logging to /home/kochigami/.ros/log/199232b6-e98b-11e5-8619-bc5ff4fcfea0/roslaunch-kochigami-desktop-26517.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/kochigami/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

started roslaunch server http://192.168.97.146:57461/

SUMMARY
========

CLEAR PARAMETERS
 * /naoqi_dashboard_aggregator/

PARAMETERS
 * /image_saver/filename_format: /tmp/pepper_camer...
 * /image_saver/save_all_image: False
 * /joy_node/autorepeat_rate: 20
 * /joy_node/deadzone: 0.3
 * /joy_node/dev: /dev/input/js0
 * /naoqi_dashboard_aggregator/analyzers/joystick/discard_stale: True
 * /naoqi_dashboard_aggregator/analyzers/joystick/find_and_remove_prefix: joy_node
 * /naoqi_dashboard_aggregator/analyzers/joystick/path: Joystick
 * /naoqi_dashboard_aggregator/analyzers/joystick/type: diagnostic_aggreg...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Computer/find_and_remove_prefix: naoqi_driver_comp...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Computer/path: Computer
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Computer/type: diagnostic_aggreg...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Joints/find_and_remove_prefix: naoqi_driver_joints:
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Joints/path: Joints
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Joints/type: diagnostic_aggreg...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/PowerSystem/find_and_remove_prefix: naoqi_driver_batt...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/PowerSystem/path: Power System
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/PowerSystem/type: diagnostic_aggreg...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/path: NAOqi
 * /naoqi_dashboard_aggregator/analyzers/naoqi/type: diagnostic_aggreg...
 * /naoqi_dashboard_aggregator/analyzers/tf/find_and_remove_prefix: tf_monitor:
 * /naoqi_dashboard_aggregator/analyzers/tf/path: TF
 * /naoqi_dashboard_aggregator/analyzers/tf/type: diagnostic_aggreg...
 * /pepper_robot/pose/pose_manager/poses/init/joint_names: ['Body']
 * /pepper_robot/pose/pose_manager/poses/init/positions: [0.0, 0.0, 1.39, ...
 * /pepper_robot/pose/pose_manager/poses/init/time_from_start: 1.5
 * /pepper_robot/pose/pose_manager/poses/zero/joint_names: ['Body']
 * /pepper_robot/pose/pose_manager/poses/zero/positions: [0.0, 0.0, 0.0, 0...
 * /pepper_robot/pose/pose_manager/poses/zero/time_from_start: 1.5
 * /pepper_robot/pose/pose_manager/xap: /home/kochigami/c...
 * /robot/name: dhcp41
 * /robot/type: pepper
 * /rosdistro: indigo
 * /rosversion: 1.11.16
 * /teleop_twist_joy/axis_angular/yaw: 3
 * /teleop_twist_joy/axis_linear/x: 1.0
 * /teleop_twist_joy/axis_linear/y: 0.0
 * /teleop_twist_joy/enable_button: 4
 * /teleop_twist_joy/enable_turbo_button: 0
 * /teleop_twist_joy/scale_angular/yaw: 1.0
 * /teleop_twist_joy/scale_augular_turbo/yaw: 1.5
 * /teleop_twist_joy/scale_linear/x: 0.7
 * /teleop_twist_joy/scale_linear/y: 0.7
 * /teleop_twist_joy/scale_linear_turbo/x: 1.5
 * /teleop_twist_joy/scale_linear_turbo/y: 1.5

NODES
  /
    image_saver (image_view/image_saver)
    joy_client (jsk_pepper_startup/joy-client.l)
    joy_node (joy/joy_node)
    naoqi_dashboard (naoqi_dashboard/naoqi_dashboard)
    naoqi_dashboard_aggregator (diagnostic_aggregator/aggregator_node)
    pepper_twitter (jsk_pepper_startup/tweet.l)
    teleop_twist_joy (teleop_twist_joy/teleop_node)
    tf_monitor (diagnostic_common_diagnostics/tf_monitor.py)
    tweet (rostwitter/tweet.py)
  /pepper_robot/pose/
    pose_controller (naoqi_pose/pose_controller.py)
    pose_manager (naoqi_pose/pose_manager.py)
  /pepper_robot/
    naoqi_driver (naoqi_driver/naoqi_driver_node)

auto-starting new master
process[master]: started with pid [28653]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 199232b6-e98b-11e5-8619-bc5ff4fcfea0
process[rosout-1]: started with pid [29498]
started core service [/rosout]
process[pepper_robot/naoqi_driver-2]: started with pid [29566]
process[pepper_robot/pose/pose_controller-3]: started with pid [29573]
process[pepper_robot/pose/pose_manager-4]: started with pid [29588]
process[joy_node-5]: started with pid [29596]
process[teleop_twist_joy-6]: started with pid [29597]
process[pepper_twitter-7]: started with pid [29631]
process[tweet-8]: started with pid [29657]
[ERROR] [1457921935.273256443]: Couldn't open joystick /dev/input/js0. Will retry every second.
process[image_saver-9]: started with pid [29672]
process[naoqi_dashboard-10]: started with pid [29680]
Receiving information about robot model
process[tf_monitor-11]: started with pid [29690]
process[naoqi_dashboard_aggregator-12]: started with pid [29706]
[W] 29566 qimessaging.remoteobject: Return signature might be incorrect depending on the value, from m to s
process[joy_client-13]: started with pid [29720]
configuring by "/opt/ros/indigo/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin [W] 29566 qimessaging.remoteobject: Return signature might be incorrect depending on the value, from m to [[m]]

connected to Xserver DISPLAY=:0
set prefix successfully to 
[I] 29566 qimessaging.session: Session listener created on tcp://0.0.0.0:0
[I] 29566 qimessaging.transportserver: TransportServer will listen on: tcp://192.168.97.146:46079
[I] 29566 qimessaging.transportserver: TransportServer will listen on: tcp://127.0.0.1:46079
configuring by "/opt/ros/indigo/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; pbmfile ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel using ip address: 192.168.97.146 @ eth1
;; trans ;; comp ;; image_correlation ;; oglforeign ;; builtins ;; par ;; gldecl ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; glconst ;; Xgraphics ;; Xcolor ;; glforeign ;; gluconst ;; Xeus ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; Xevent ;; toiv-undefined ;; fstringdouble ;; Xpanel ;; Xitem irtmath ;; Xtext irtutil irtc irtgeoc irtgraph ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin pgsql 
connected to Xserver DISPLAY=:0
found a catkin prefix /home/kochigami/catkin_ws/src/naoqi_driver/share/boot_config.json
load boot config from /home/kochigami/catkin_ws/src/naoqi_driver/share/boot_config.json
irtgeo euspqp pqp irtscene irtmodel X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage irtdyna ;; pbmfile ;; image_correlation ;; oglforeign irtrobot irtsensor ;; gldecl irtbvh ;; glconst irtcollada irtpointcloud irtx ;; glforeign ;; gluconst ;; gluforeign ;; glxconst eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x4d9ade0[16374] --> 0x51f8f10[32748] top=3c6d
;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph pgsql irtgl [INFO] [WallTime: 1457921935.578486] Connecting to NaoQi at 192.168.97.41:9559
irtgeo euspqp pqp irtscene irtmodel irtviewer [I] 29573 qimessaging.session: Session listener created on tcp://0.0.0.0:0
[I] 29573 qimessaging.transportserver: TransportServer will listen on: tcp://192.168.97.146:36767
[I] 29573 qimessaging.transportserver: TransportServer will listen on: tcp://127.0.0.1:36767

EusLisp 9.16( 1.0.11) for Linux64 created on host04.storm.ros.org(Wed Nov 11 00:20:12 UTC 2015)
irtdyna irtrobot irtsensor irtbvh roseus ;; loading roseus("") on euslisp((9.16 host04.storm.ros.org Wed Nov 11 00:20:12 UTC 2015  1.0.11))
irtcollada irtpointcloud eustf irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x63c0de0[16374] --> 0x681ef10[32748] top=3c6d
irtgl irtviewer 
EusLisp 9.16( 1.0.11) for Linux64 created on host04.storm.ros.org(Wed Nov 11 00:20:12 UTC 2015)
roseus ;; loading roseus("") on euslisp((9.16 host04.storm.ros.org Wed Nov 11 00:20:12 UTC 2015  1.0.11))
eustf [WARN] [WallTime: 1457921935.735097] Collection LLeg not found on your robot.
[WARN] [WallTime: 1457921935.738326] Collection RLeg not found on your robot.
roseus_c_util roseus_c_util [INFO] [WallTime: 1457921935.892863] nao_controller initialized
[INFO] [WallTime: 1457921935.893285] nao pose_controller running...
[WARN] [WallTime: 1457921937.955987] stop_walk_srv not available, pose_manager will not stop the walker before executing a trajectory. This is normal if there is no nao_walker running.
[ERROR] [WallTime: 1457921951.099293] /tweet /tmp/pepper_camera.png could not find　　###ここで止まる###
no camera information found for camera_source 3 and res: 1 ###naoqi_driverの立ち上げに関するところ###
found a catkin URDF /home/kochigami/catkin_ws/src/naoqi_driver/share/urdf/pepper.urdf
Audio Extractor: Start
RightBumperPressed
LeftBumperPressed
BackBumperPressed
ROS-Driver-RightBumperPressed : Start
FrontTactilTouched
MiddleTactilTouched
RearTactilTouched
ROS-Driver-FrontTactilTouched : Start
HandRightBackTouched
HandRightLeftTouched
HandRightRightTouched
HandLeftBackTouched
HandLeftLeftTouched
HandLeftRightTouched
ROS-Driver-HandRightBackTouched : Start
registered subscriber:	teleop
registered subscriber:	moveto
registered subscriber:	speech
registered subscriber:	animated_speech
nodehandle reset 
using master ip: http://192.168.97.146:11311
NOT going to re-register the converters
camera/bottom/image_raw is resetting
camera/bottom/image_raw reset
camera/depth/image_raw is resetting
camera/depth/image_raw reset
/diagnostics is resetting
/diagnostics reset
camera/front/image_raw is resetting
camera/front/image_raw reset
imu/base is resetting
imu/base reset
imu/torso is resetting
imu/torso reset
info is resetting
load robot description from file
info reset
camera/ir/image_raw is resetting
camera/ir/image_raw reset
/joint_states is resetting
/joint_states reset
laser is resetting
laser reset
/rosout is resetting
/rosout reset
sonar is resetting
sonar reset
resetting subscriber teleop
teleop is resetting
teleop reset
resetting subscriber moveto
moveto is resetting
moveto reset
resetting subscriber speech
speech is resetting
speech reset
resetting subscriber animated_speech
animated_speech is resetting
animated_speech reset
resetting service robot config service
robot config service is resetting
```

**Comment by kochigami** [comment]
I think it's different from the problem mentioned above: roslaunch jsk_pepper_startup jsk_pepper_startup.launch sometimes fails. 
I use ubuntu 14.04, ros indigo, naoqi_driver from source (master branch , top commit is "0.5.8" )

- yesterday I updated my naoqi_driver package
- I have to wait for a long time before launching my other programs?
- my created programs do bad things on jsk_pepper_startup? (<=> after trying three times, my programs seem to work properly.)

- [ ] see commits of naoqi_driver
- [ ] wait for a while and then launching my other programs
- [ ] check topic names of my programs

I think this part is problem.
```
[WARN] [WallTime: 1464073031.515735] unable to communicate with ROS Master, registrations are now out of sync
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/diagnostic_common_diagnostics/tf_monitor.py", line 185, in <module>
    diag_updater.update()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/diagnostic_updater/_diagnostic_updater.py", line 245, in update
    self._check_diagnostic_period()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/diagnostic_updater/_diagnostic_updater.py", line 320, in _check_diagnostic_period
    self.period = rospy.get_param("~diagnostic_period", 1)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 462, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msproxy.py", line 121, in __getitem__
    code, msg, value = self.target.getParam(rospy.names.get_caller_id(), resolved_key)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
[tf_monitor-10] process has died [pid 27185, exit code 1, cmd /opt/ros/indigo/lib/diagnostic_common_diagnostics/tf_monitor.py __name:=tf_monitor __log:=/home/kochigami/.ros/log/4c7438a4-217c-11e6-9d6a-bc5ff4fcfea0/tf_monitor-10.log].
log file: /home/kochigami/.ros/log/4c7438a4-217c-11e6-9d6a-bc5ff4fcfea0/tf_monitor-10*.log
```


All launching message is below.
```
roslaunch jsk_pepper_startup jsk_pepper_startup.launch network_interface:=eth1
... logging to /home/kochigami/.ros/log/4c7438a4-217c-11e6-9d6a-bc5ff4fcfea0/roslaunch-kochigami-desktop-27099.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/kochigami/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

started roslaunch server http://192.168.97.25:45190/

SUMMARY
========

CLEAR PARAMETERS
 * /naoqi_dashboard_aggregator/

PARAMETERS
 * /image_saver/filename_format: /tmp/pepper_camer...
 * /image_saver/save_all_image: False
 * /joy_node/autorepeat_rate: 20
 * /joy_node/deadzone: 0.3
 * /joy_node/dev: /dev/input/js0
 * /naoqi_dashboard_aggregator/analyzers/joystick/discard_stale: True
 * /naoqi_dashboard_aggregator/analyzers/joystick/find_and_remove_prefix: joy_node
 * /naoqi_dashboard_aggregator/analyzers/joystick/path: Joystick
 * /naoqi_dashboard_aggregator/analyzers/joystick/type: diagnostic_aggreg...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Computer/find_and_remove_prefix: naoqi_driver_comp...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Computer/path: Computer
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Computer/type: diagnostic_aggreg...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Joints/find_and_remove_prefix: naoqi_driver_joints:
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Joints/path: Joints
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/Joints/type: diagnostic_aggreg...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/PowerSystem/find_and_remove_prefix: naoqi_driver_batt...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/PowerSystem/path: Power System
 * /naoqi_dashboard_aggregator/analyzers/naoqi/analyzers/PowerSystem/type: diagnostic_aggreg...
 * /naoqi_dashboard_aggregator/analyzers/naoqi/path: NAOqi
 * /naoqi_dashboard_aggregator/analyzers/naoqi/type: diagnostic_aggreg...
 * /naoqi_dashboard_aggregator/analyzers/tf/find_and_remove_prefix: tf_monitor:
 * /naoqi_dashboard_aggregator/analyzers/tf/path: TF
 * /naoqi_dashboard_aggregator/analyzers/tf/type: diagnostic_aggreg...
 * /pepper_robot/pose/pose_manager/poses/init/joint_names: ['Body']
 * /pepper_robot/pose/pose_manager/poses/init/positions: [0.0, 0.0, 1.39, ...
 * /pepper_robot/pose/pose_manager/poses/init/time_from_start: 1.5
 * /pepper_robot/pose/pose_manager/poses/zero/joint_names: ['Body']
 * /pepper_robot/pose/pose_manager/poses/zero/positions: [0.0, 0.0, 0.0, 0...
 * /pepper_robot/pose/pose_manager/poses/zero/time_from_start: 1.5
 * /pepper_robot/pose/pose_manager/xap: /home/kochigami/c...
 * /robot/name: dhcp87
 * /robot/type: pepper
 * /rosdistro: indigo
 * /rosversion: 1.11.19
 * /teleop_twist_joy/axis_angular/yaw: 3
 * /teleop_twist_joy/axis_linear/x: 1.0
 * /teleop_twist_joy/axis_linear/y: 0.0
 * /teleop_twist_joy/enable_button: 4
 * /teleop_twist_joy/enable_turbo_button: 0
 * /teleop_twist_joy/scale_angular/yaw: 1.0
 * /teleop_twist_joy/scale_augular_turbo/yaw: 1.5
 * /teleop_twist_joy/scale_linear/x: 0.7
 * /teleop_twist_joy/scale_linear/y: 0.7
 * /teleop_twist_joy/scale_linear_turbo/x: 1.5
 * /teleop_twist_joy/scale_linear_turbo/y: 1.5

NODES
  /
    image_saver (image_view/image_saver)
    joy_client (jsk_pepper_startup/joy-client.l)
    joy_node (joy/joy_node)
    naoqi_dashboard (naoqi_dashboard/naoqi_dashboard)
    naoqi_dashboard_aggregator (diagnostic_aggregator/aggregator_node)
    pepper_twitter (jsk_pepper_startup/tweet.l)
    teleop_twist_joy (teleop_twist_joy/teleop_node)
    tf_monitor (diagnostic_common_diagnostics/tf_monitor.py)
    tweet (rostwitter/tweet.py)
  /pepper_robot/pose/
    pose_controller (naoqi_pose/pose_controller.py)
    pose_manager (naoqi_pose/pose_manager.py)
  /pepper_robot/
    naoqi_driver (naoqi_driver/naoqi_driver_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[pepper_robot/naoqi_driver-1]: started with pid [27123]
process[pepper_robot/pose/pose_controller-2]: started with pid [27124]
process[pepper_robot/pose/pose_manager-3]: started with pid [27125]
process[joy_node-4]: started with pid [27126]
process[teleop_twist_joy-5]: started with pid [27127]
process[pepper_twitter-6]: started with pid [27135]
process[tweet-7]: started with pid [27151]
process[image_saver-8]: started with pid [27161]
[ERROR] [1464072921.579928041]: Couldn't open joystick /dev/input/js0. Will retry every second.
process[naoqi_dashboard-9]: started with pid [27180]
Receiving information about robot model
process[tf_monitor-10]: started with pid [27185]
process[naoqi_dashboard_aggregator-11]: started with pid [27198]
[W] 27123 qimessaging.remoteobject: Return signature might be incorrect depending on the value, from m to s
process[joy_client-12]: started with pid [27210]
configuring by "/opt/ros/indigo/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus [W] 27123 qimessaging.remoteobject: Return signature might be incorrect depending on the value, from m to [[m]]
;; Xevent ;; Xpanel ;; Xitem set prefix successfully to 
[I] 27123 qimessaging.session: Session listener created on tcp://0.0.0.0:0
;; Xtext [I] 27123 qimessaging.transportserver: TransportServer will listen on: tcp://192.168.97.25:57958
[I] 27123 qimessaging.transportserver: TransportServer will listen on: tcp://127.0.0.1:57958
;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin using ip address: 192.168.97.25 @ eth1

connected to Xserver DISPLAY=:0
configuring by "/opt/ros/indigo/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; pbmfile ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; image_correlation ;; oglforeign ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; gldecl ;; glconst ;; Xgraphics ;; Xcolor ;; Xeus ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph 
connected to Xserver DISPLAY=:0
pgsql X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage found a catkin prefix /home/kochigami/catkin_ws/src/naoqi_driver/share/boot_config.json
load boot config from /home/kochigami/catkin_ws/src/naoqi_driver/share/boot_config.json
;; pbmfile irtgeo ;; image_correlation ;; oglforeign euspqp pqp irtscene irtmodel ;; gldecl ;; glconst irtdyna irtrobot irtsensor ;; glforeign ;; gluconst ;; gluforeign irtbvh ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview irtcollada ;; toiv-undefined ;; fstringdouble irtpointcloud irtmath irtutil irtc irtgeoc irtgraph irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x583cde0[16374] --> 0x5c9af10[32748] top=3c7e
pgsql irtgl irtgeo euspqp pqp irtscene irtmodel irtviewer 
EusLisp 9.19( 1.0.12) for Linux64 created on ip-172-31-15-39(Thu May 5 01:33:05 PDT 2016)
irtdyna irtrobot irtsensor irtbvh roseus ;; loading roseus("") on euslisp((9.19 ip-172-31-15-39 Thu May 5 01:33:05 PDT 2016  1.0.12))
irtcollada irtpointcloud irtx eusjpeg euspng png irtimage irtglrgb eustf 
;; extending gcstack 0x599ade0[16374] --> 0x5df8f10[32748] top=3c7e
irtgl irtviewer 
EusLisp 9.19( 1.0.12) for Linux64 created on ip-172-31-15-39(Thu May 5 01:33:05 PDT 2016)
roseus ;; loading roseus("") on euslisp((9.19 ip-172-31-15-39 Thu May 5 01:33:05 PDT 2016  1.0.12))
[INFO] [WallTime: 1464072922.065954] Connecting to NaoQi at 192.168.97.87:9559
eustf [I] 27124 qimessaging.session: Session listener created on tcp://0.0.0.0:0
[I] 27124 qimessaging.transportserver: TransportServer will listen on: tcp://192.168.97.25:38044
[I] 27124 qimessaging.transportserver: TransportServer will listen on: tcp://127.0.0.1:38044
roseus_c_util [WARN] [WallTime: 1464072922.200799] Collection LLeg not found on your robot.
[WARN] [WallTime: 1464072922.212013] Collection RLeg not found on your robot.
roseus_c_util [INFO] [WallTime: 1464072922.334406] nao_controller initialized
[INFO] [WallTime: 1464072922.334849] nao pose_controller running...
no camera information found for camera_source 3 and res: 1
found a catkin URDF /home/kochigami/catkin_ws/src/naoqi_driver/share/urdf/pepper.urdf
Audio Extractor: Start
RightBumperPressed
LeftBumperPressed
BackBumperPressed
ROS-Driver-RightBumperPressed : Start
FrontTactilTouched
MiddleTactilTouched
RearTactilTouched
ROS-Driver-FrontTactilTouched : Start
registered subscriber:	teleop
registered subscriber:	moveto
registered subscriber:	speech
nodehandle reset 
using master ip: http://192.168.97.25:11311
NOT going to re-register the converters
camera/bottom/image_raw is resetting
camera/bottom/image_raw reset
camera/depth/image_raw is resetting
camera/depth/image_raw reset
/diagnostics is resetting
/diagnostics reset
camera/front/image_raw is resetting
camera/front/image_raw reset
imu/base is resetting
imu/base reset
imu/torso is resetting
imu/torso reset
info is resetting
load robot description from file
info reset
camera/ir/image_raw is resetting
camera/ir/image_raw reset
/joint_states is resetting
/joint_states reset
laser is resetting
laser reset
/rosout is resetting
/rosout reset
sonar is resetting
sonar reset
resetting subscriber teleop
teleop is resetting
teleop reset
resetting subscriber moveto
moveto is resetting
moveto reset
resetting subscriber speech
speech is resetting
speech reset
resetting service robot config service
robot config service is resetting
resetting service speech recognition service
speech recognition service is resetting
resetting service speech recognition service
speech recognition service is resetting
[WARN] [WallTime: 1464072924.441360] stop_walk_srv not available, pose_manager will not stop the walker before executing a trajectory. This is normal if there is no nao_walker running.
[ERROR] [WallTime: 1464072938.197565] /tweet /tmp/pepper_camera.png could not find
[WARN] [WallTime: 1464073031.515735] unable to communicate with ROS Master, registrations are now out of sync
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/diagnostic_common_diagnostics/tf_monitor.py", line 185, in <module>
    diag_updater.update()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/diagnostic_updater/_diagnostic_updater.py", line 245, in update
    self._check_diagnostic_period()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/diagnostic_updater/_diagnostic_updater.py", line 320, in _check_diagnostic_period
    self.period = rospy.get_param("~diagnostic_period", 1)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 462, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msproxy.py", line 121, in __getitem__
    code, msg, value = self.target.getParam(rospy.names.get_caller_id(), resolved_key)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
[tf_monitor-10] process has died [pid 27185, exit code 1, cmd /opt/ros/indigo/lib/diagnostic_common_diagnostics/tf_monitor.py __name:=tf_monitor __log:=/home/kochigami/.ros/log/4c7438a4-217c-11e6-9d6a-bc5ff4fcfea0/tf_monitor-10.log].
log file: /home/kochigami/.ros/log/4c7438a4-217c-11e6-9d6a-bc5ff4fcfea0/tf_monitor-10*.log

```

**Comment by k-okada** [comment]
please make sure that you do not have existing roscore service (`ps -auxwww
| grep rosmaster` or reboot) and run again, if it does not help, please
provide following information
```
env | grep ROS
cat /etc/hosts
ifconfig -a
```


--
◉ Kei Okada

**Comment by kochigami** [comment]
I'm sorry for keeping this issue open for a long time.
Recently, I haven't met the situation.

If the same problem occurs, I'll re-open the issue.
